version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          test_command: check
          test_results_path: build/test-results/
          reports_path: build/reports/
